server:
  port: 8085

spring:
  application:
    name: community-service
  couchbase:
    connection-string: couchbase://localhost
    user-name: admin
    password: password
  data:
    couchbase:
      bucket-name: community
      
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/MotoNexus
